name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  api_calls:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate and use Bearer Token
        run: |
          # 1. Authenticate and get the bearer token (replace with your auth endpoint and credentials)
          TOKEN=$(curl -s -X POST "https://your-auth-endpoint.com/token" \
            -H "Content-Type: application/json" \
            -d '{"username":"youruser","password":"yourpass"}' | jq -r '.access_token')

          echo "Received token: $TOKEN"

          # 2. Use the bearer token in the next API call
          curl -X POST "https://your-api-endpoint.com/your-action" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"key":"value"}'
