name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ... your other steps ...

      - name: Call API with curl
        run: |
          curl -X POST https://your.api/endpoint \
            -H "Content-Type: application/json" \
            -d '{"key":"value"}'
